export enum UserActionType {
  ADD_HISTORY,
  ADD_LIKED_VIDEO,
  ADD_WATCH_LATER,
  DEL_HISTORY,
  DEL_WATCH_LATER,
  DEL_LIKED_VIDEO,
  LOGIN,
  LOGOUT,
  ADD_PLAYLIST,
  DEL_PLAYLIST,
  ADD_PLAYLIST_VIDEO,
  DEL_PLAYLIST_VIDEO,
}
